In [6]:
import torch

In [10]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [11]:
# create random data
torch.manual_seed(10)

# Features are 5 random variables
features=torch.randn(1,5)

# Define the size of each layer in NN
n_input=features.shape[1]  # no of input units must match with input features
n_hidden=2                 # no of hidden units
n_output=1                 # no of output units

#weights for input to hidden layer
w1=torch.randn(n_input,n_hidden)

# weights for hidden to output layer
w2=torch.randn(n_hidden,n_output)

# Bias terms for hidden and output layer
b1=torch.randn(1,n_hidden)
b2=torch.randn(1,n_output)

In [13]:
# create output for multilayer NN

h=activation(torch.mm(features,w1)+b1)
y=activation(torch.mm(h,w2)+b2)
print(y)

tensor([[0.6429]])


## Conversion between numpy array and torch tensors
* `torch.from_numpy(var)`  numpy to tensor
* `tensor.numpy()`      tensor to numpy

In [21]:
import numpy as np
a=np.random.rand(4,3)
print(a)

# convert to tensor
b=torch.from_numpy(a)
print(b)

# convert to numpy
b.numpy()

[[0.22030399 0.02066936 0.34933094]
 [0.52852816 0.87843255 0.44364433]
 [0.88360037 0.53087783 0.59276631]
 [0.38980349 0.59443321 0.82679226]]
tensor([[0.2203, 0.0207, 0.3493],
        [0.5285, 0.8784, 0.4436],
        [0.8836, 0.5309, 0.5928],
        [0.3898, 0.5944, 0.8268]], dtype=torch.float64)


array([[0.22030399, 0.02066936, 0.34933094],
       [0.52852816, 0.87843255, 0.44364433],
       [0.88360037, 0.53087783, 0.59276631],
       [0.38980349, 0.59443321, 0.82679226]])

## memory is shared in between Numpy array  and Torch tensors , so changing values in place in one object will change in other

In [22]:
b.mul_(2)

tensor([[0.4406, 0.0413, 0.6987],
        [1.0571, 1.7569, 0.8873],
        [1.7672, 1.0618, 1.1855],
        [0.7796, 1.1889, 1.6536]], dtype=torch.float64)

In [23]:
print(a)

[[0.44060799 0.04133872 0.69866189]
 [1.05705633 1.7568651  0.88728866]
 [1.76720075 1.06175565 1.18553262]
 [0.77960698 1.18886642 1.65358451]]
