In [1]:
import torch

In [5]:
def activation(x):
    """ Sigmoid activation 
        function argiments
    """
    return 1/(1+torch.exp(-x))

In [6]:
# generate some random data
torch.manual_seed(10)  # set random seeds so things are predictable

# features are 5 random normal variables
features=torch.randn(1,5)

# true weights for data, random normal variables again
weights=torch.randn_like(features)

# true bias term
bias=torch.randn((1,1))   # one element i.e 1 row an 1 column


In [15]:
# small NN
y=activation(torch.sum(features*weights)+bias)
print(y)

y=activation((features*weights).sum()+bias)
print(y)

tensor([[0.9748]])
tensor([[0.9748]])


## use `matrix multiplication` because it does multiplication and sum in one operation
* torch.mm(m1,m2)
* torch.matmul(m1,m2)

In [17]:
# torch.mm(features,weights) gives error size mismatch
## reshape weights tensor 

## reshape  tensor functions
* tensor.reshape(a,b)  returns new tensor
* tensor.resize(a,b)  returns same tensor with new size
* tensor.view(a,b)    returns new tensor 

In [18]:
weights.shape

torch.Size([1, 5])

In [21]:
weights.resize_(5,1)
weights.shape

torch.Size([5, 1])

In [22]:
torch.mm(features,weights)

tensor([[4.5947]])

In [23]:
# output using matrix multiplication
y=activation(torch.mm(features,weights)+bias)
print(y)

tensor([[0.9748]])
